repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^.*\.rst$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: [pytest]
