name: main

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: ${{ matrix.os }}) - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [
          ubuntu-latest,
          window-latest,
          macos-latest
        ]
        tox-env: [
          py38,
          py39,
          py310,
        ]
        include:
          # create additional matrix entries for ubuntu & tox_env
          - tox-env: lint
            os: ubuntu-latest
          - tox-env: coverage
            os: ubuntu-latest

          # set env vars for tox (python-version)
          - tox-env: py38
            python-version: "3.8"
          - tox-env: py39
            python-version: "3.9"
          - tox-env: py310
            python-version: "3.10"
          - tox-env: linting
            python-version: "3.10"
          - tox-env: coverage
            python-version: "3.10"

          # set vars for conda-forge (conda-forge-os)
          - os: ubuntu-latest
            conda-forge-os: Linux
          - os: windows-latest
            conda-forge-os: Windows
          - os: macos-latest
            conda-forge-os: MacOSX

          # set vars for conda-forge (conda-forge-arch)
          - runner.arch: X86
            conda-forge-arch: X86_64
          - runner.arch: X64
            conda-forge-arch: X86_64
          - runner.arch: ARM
            os: ubuntu-latest
            # cspell: disable-next-line
            conda-forge-arch: aarch64
          - runner.arch: ARM
            os: macos-latest
            conda-forge-arch: arm64
          - runner.arch: ARM64
            os: ubuntu-latest
            # cspell: disable-next-line
            conda-forge-arch: aarch64

          # set vars for conda-forge (conda-forge-ext)
          - os: ubuntu-latest
            conda-forge-ext: sh
          - os: window-latest
            conda-forge-ext: exe
          - os: macos-latest
            conda-forge-ext: sh

    steps:
      - uses: actions/checkout@v1
      - name: Setup miniforge
        uses: goanpeca/setup-miniconda@v1
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-${{ matrix.conda-forge-os }}-${{ matrix.conda-forge-arch }}.${{ matrix.conda-forge-ext }}
          python-version: ${{ env.PYTHON_LATEST }}
          allow-softlinks: true
          show-channel-urls: true
          auto-activate-base: false
      - name: Conda Base Info
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Conda Env Setup
        run: |
          conda env create --name work --file ./conda-environment.yml -v

      - name: Poetry Dependencies
        run: |
          conda activate work
          poetry install

      - name: Test
        run: |
          conda activate work
          tox -e ${{ matrix.tox-env }}


  # deploy:
  #   if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

  #   runs-on: ubuntu-latest
  #   needs: poetry

  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Set up Python
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: "3.10"
  #   - name: Install wheel
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install wheel setuptools
  #   - name: Build package
  #     run: |
  #       python setup.py sdist bdist_wheel
  #   - name: Publish package to PyPI
  #     uses: pypa/gh-action-pypi-publish@master
  #     with:
  #       user: __token__
  #       password: ${{ secrets.pypi_token }}
